// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: operations.sql

package repository

import (
	"context"
)

const createOperation = `-- name: CreateOperation :one
INSERT INTO operations (file_id, version, operation)
VALUES (?, ?, ?)
RETURNING file_id, version, operation, created_at
`

type CreateOperationParams struct {
	FileID    int64  `json:"fileId"`
	Version   int64  `json:"version"`
	Operation string `json:"operation"`
}

func (q *Queries) CreateOperation(ctx context.Context, arg CreateOperationParams) (Operation, error) {
	row := q.db.QueryRowContext(ctx, createOperation, arg.FileID, arg.Version, arg.Operation)
	var i Operation
	err := row.Scan(
		&i.FileID,
		&i.Version,
		&i.Operation,
		&i.CreatedAt,
	)
	return i, err
}

const fetchFileOperationsFromVersion = `-- name: FetchFileOperationsFromVersion :many
SELECT file_id, version, operation, created_at
FROM operations
WHERE file_id = ? AND version > ?
ORDER BY version ASC
`

type FetchFileOperationsFromVersionParams struct {
	FileID  int64 `json:"fileId"`
	Version int64 `json:"version"`
}

func (q *Queries) FetchFileOperationsFromVersion(ctx context.Context, arg FetchFileOperationsFromVersionParams) ([]Operation, error) {
	rows, err := q.db.QueryContext(ctx, fetchFileOperationsFromVersion, arg.FileID, arg.Version)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Operation
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.FileID,
			&i.Version,
			&i.Operation,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchOperation = `-- name: FetchOperation :one
SELECT file_id, version, operation, created_at
FROM operations
WHERE file_id = ? AND version = ?
LIMIT 1
`

type FetchOperationParams struct {
	FileID  int64 `json:"fileId"`
	Version int64 `json:"version"`
}

func (q *Queries) FetchOperation(ctx context.Context, arg FetchOperationParams) (Operation, error) {
	row := q.db.QueryRowContext(ctx, fetchOperation, arg.FileID, arg.Version)
	var i Operation
	err := row.Scan(
		&i.FileID,
		&i.Version,
		&i.Operation,
		&i.CreatedAt,
	)
	return i, err
}
