// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: snapshots.sql

package repository

import (
	"context"
)

const createSnapshot = `-- name: CreateSnapshot :exec
INSERT INTO snapshots (file_id, version, disk_path, type, hash, workspace_id)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateSnapshotParams struct {
	FileID      int64  `json:"fileId"`
	Version     int64  `json:"version"`
	DiskPath    string `json:"diskPath"`
	Type        string `json:"type"`
	Hash        string `json:"hash"`
	WorkspaceID int64  `json:"workspaceId"`
}

func (q *Queries) CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, createSnapshot,
		arg.FileID,
		arg.Version,
		arg.DiskPath,
		arg.Type,
		arg.Hash,
		arg.WorkspaceID,
	)
	return err
}

const deleteSnapshotsForFile = `-- name: DeleteSnapshotsForFile :exec
DELETE FROM snapshots
WHERE file_id = ?
`

func (q *Queries) DeleteSnapshotsForFile(ctx context.Context, fileID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSnapshotsForFile, fileID)
	return err
}

const fetchLatestSnapshotForFile = `-- name: FetchLatestSnapshotForFile :one
SELECT file_id, version, disk_path, hash, created_at, type, workspace_id
FROM snapshots
WHERE file_id = ?
ORDER BY created_at DESC, version DESC
LIMIT 1
`

func (q *Queries) FetchLatestSnapshotForFile(ctx context.Context, fileID int64) (Snapshot, error) {
	row := q.db.QueryRowContext(ctx, fetchLatestSnapshotForFile, fileID)
	var i Snapshot
	err := row.Scan(
		&i.FileID,
		&i.Version,
		&i.DiskPath,
		&i.Hash,
		&i.CreatedAt,
		&i.Type,
		&i.WorkspaceID,
	)
	return i, err
}

const fetchSnapshotByVersion = `-- name: FetchSnapshotByVersion :one
SELECT file_id, version, disk_path, hash, created_at, type, workspace_id
FROM snapshots
WHERE file_id = ?
  AND version = ?
  AND workspace_id = ?
`

type FetchSnapshotByVersionParams struct {
	FileID      int64 `json:"fileId"`
	Version     int64 `json:"version"`
	WorkspaceID int64 `json:"workspaceId"`
}

func (q *Queries) FetchSnapshotByVersion(ctx context.Context, arg FetchSnapshotByVersionParams) (Snapshot, error) {
	row := q.db.QueryRowContext(ctx, fetchSnapshotByVersion, arg.FileID, arg.Version, arg.WorkspaceID)
	var i Snapshot
	err := row.Scan(
		&i.FileID,
		&i.Version,
		&i.DiskPath,
		&i.Hash,
		&i.CreatedAt,
		&i.Type,
		&i.WorkspaceID,
	)
	return i, err
}

const fetchSnapshots = `-- name: FetchSnapshots :many
SELECT file_id, version, disk_path, hash, created_at, type, workspace_id
FROM snapshots
WHERE file_id = ?
  AND workspace_id = ?
ORDER BY created_at DESC, version DESC
`

type FetchSnapshotsParams struct {
	FileID      int64 `json:"fileId"`
	WorkspaceID int64 `json:"workspaceId"`
}

func (q *Queries) FetchSnapshots(ctx context.Context, arg FetchSnapshotsParams) ([]Snapshot, error) {
	rows, err := q.db.QueryContext(ctx, fetchSnapshots, arg.FileID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Snapshot
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.FileID,
			&i.Version,
			&i.DiskPath,
			&i.Hash,
			&i.CreatedAt,
			&i.Type,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
